minimumReleaseAge: 0
strictDepBuilds: false

minimumReleaseAgeExclude:
  - '@replit/*'
  - stripe-replit-sync

packages:
  - artifacts/*

autoInstallPeers: false

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver
  - '@google/genai'
  - protobufjs

allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
