import React, { useMemo, useState } from 'react';
import { useERP } from '../lib/store';
import { CalendarClock, CircleDollarSign, FileWarning, Phone, Search, WalletCards, CheckCircle2 } from 'lucide-react';

const money = (value: number) => `${value.toLocaleString('tr-TR')} ₺`;
const daysSince = (date?: string) => date ? Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 86400000)) : 0;

export const PaymentPlanningPage: React.FC = () => {
  const { customers, invoices, collections, payments, jobReceipts, addCollection, addPayment, markCollectionReceived, markPaymentPaid } = useERP();
  const [tab, setTab] = useState<'collections' | 'payments' | 'receipts'>('collections');
  const [search, setSearch] = useState('');
  const [planCustomer, setPlanCustomer] = useState('');
  const [planAmount, setPlanAmount] = useState('');
  const [planDate, setPlanDate] = useState(new Date().toISOString().slice(0, 10));
  const [planNote, setPlanNote] = useState('');
  const normalizedSearch = search.toLocaleLowerCase('tr-TR');

  const customerDebt = useMemo(() => customers.map((customer) => {
    const customerInvoices = invoices.filter((invoice) => invoice.customerId === customer.id && !['paid', 'odendi', 'cancelled'].includes(invoice.status));
    const pending = collections.filter((item) => item.customerId === customer.id && item.status === 'bekliyor');
    const lastDue = customerInvoices.map((invoice) => invoice.dueDate).sort()[0];
    return { customer, invoiceTotal: customerInvoices.reduce((sum, invoice) => sum + Math.max(0, invoice.totalAmount - invoice.paidAmount), 0), pendingTotal: pending.reduce((sum, item) => sum + item.amount, 0), oldestDays: daysSince(lastDue), lastDue };
  }).filter((item) => item.customer.balance > 0 || item.invoiceTotal > 0 || item.pendingTotal > 0).sort((a, b) => b.oldestDays - a.oldestDays), [customers, invoices, collections]);

  const uninvoiced = jobReceipts.filter((receipt) => ['approved', 'onaylandi'].includes(receipt.status) && !receipt.invoiced).filter((receipt) => !normalizedSearch || receipt.customerName.toLocaleLowerCase('tr-TR').includes(normalizedSearch));
  const filteredDebts = customerDebt.filter((item) => !normalizedSearch || `${item.customer.title} ${item.customer.phone} ${item.customer.authorizedPerson || ''}`.toLocaleLowerCase('tr-TR').includes(normalizedSearch));
  const scheduledPayments = payments.filter((item) => item.status === 'bekliyor').filter((item) => !normalizedSearch || item.recipientName.toLocaleLowerCase('tr-TR').includes(normalizedSearch));
  const receivedCash = collections.filter((item) => item.status === 'tahsil_edildi').reduce((sum, item) => sum + item.amount, 0);
  const paidCash = payments.filter((item) => item.status === 'odendi').reduce((sum, item) => sum + item.amount, 0);
  const plannedIn = collections.filter((item) => item.status === 'bekliyor').reduce((sum, item) => sum + item.amount, 0);
  const plannedOut = payments.filter((item) => item.status === 'bekliyor').reduce((sum, item) => sum + item.amount, 0);

  const createCollectionPlan = async (event: React.FormEvent) => {
    event.preventDefault();
    const customer = customers.find((item) => item.id === planCustomer);
    if (!customer || !planAmount) return;
    await addCollection({ customerId: customer.id, customerName: customer.title, amount: Number(planAmount), date: planDate, dueDate: planDate, paymentMethod: 'havale', status: 'bekliyor', notes: planNote || 'Tahsilat planı' });
    setPlanAmount(''); setPlanNote('');
  };

  const createPaymentPlan = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!planCustomer || !planAmount) return;
    await addPayment({ recipientType: 'tedarikci', recipientName: planCustomer, category: 'diger', amount: Number(planAmount), dueDate: planDate, paymentMethod: 'havale', status: 'bekliyor', notes: planNote || 'Ödeme planı' });
    setPlanAmount(''); setPlanNote('');
  };

  return <main className="space-y-6 animate-in fade-in duration-150">
    <section className="rounded-[26px] bg-gradient-to-br from-emerald-950 via-emerald-800 to-emerald-600 text-white p-6 shadow-xl"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-lime-200">Muhasebe karar ekranı</p><h1 className="mt-2 text-3xl font-black">Ödeme & Tahsilat Planlama</h1><p className="mt-2 text-sm text-emerald-50/80 max-w-2xl">Cari bakiyeleri, vadesi geçmiş alacakları, planlanan ödemeleri ve fatura bekleyen iş makbuzlarını tek akışta yönetin.</p></div><div className="grid grid-cols-2 gap-2 text-xs"><div className="rounded-2xl bg-white/10 border border-white/15 p-3"><span className="text-emerald-100">Cari alacak</span><b className="block text-xl mt-1">{money(customerDebt.reduce((sum, item) => sum + Math.max(item.customer.balance, item.invoiceTotal), 0))}</b></div><div className="rounded-2xl bg-white/10 border border-white/15 p-3"><span className="text-emerald-100">Faturasız iş</span><b className="block text-xl mt-1">{uninvoiced.length}</b></div></div></div></section>
    <section className="grid grid-cols-2 lg:grid-cols-5 gap-3"><div className="rounded-2xl bg-white border border-emerald-100 p-4 shadow-sm"><span className="text-[10px] font-bold uppercase text-slate-500">Banka/kasa net hareket</span><b className="block mt-1 text-xl text-emerald-900">{money(receivedCash - paidCash)}</b><span className="text-[10px] text-slate-500">Gerçekleşen tahsilat − ödeme</span></div><div className="rounded-2xl bg-white border border-emerald-100 p-4 shadow-sm"><span className="text-[10px] font-bold uppercase text-slate-500">Planlanan giriş</span><b className="block mt-1 text-xl text-emerald-700">{money(plannedIn)}</b></div><div className="rounded-2xl bg-white border border-emerald-100 p-4 shadow-sm"><span className="text-[10px] font-bold uppercase text-slate-500">Planlanan çıkış</span><b className="block mt-1 text-xl text-rose-700">{money(plannedOut)}</b></div><div className="rounded-2xl bg-white border border-emerald-100 p-4 shadow-sm"><span className="text-[10px] font-bold uppercase text-slate-500">Beklenen net</span><b className="block mt-1 text-xl text-emerald-900">{money(plannedIn - plannedOut)}</b></div><div className="rounded-2xl bg-amber-50 border border-amber-200 p-4 shadow-sm"><span className="text-[10px] font-bold uppercase text-amber-800">Vakıf Katılım / P@ket</span><b className="block mt-1 text-sm text-amber-950">Bağlantı hazırlığı</b><span className="text-[10px] text-amber-800">API bilgileri bekleniyor</span></div></section>
    <div className="flex flex-col lg:flex-row gap-3 justify-between"><div className="flex flex-wrap gap-2"><button onClick={() => setTab('collections')} className={`px-4 py-2.5 rounded-xl text-xs font-black ${tab === 'collections' ? 'bg-emerald-600 text-white' : 'bg-white border border-emerald-200 text-emerald-800'}`}><CircleDollarSign size={14} className="inline mr-1" /> Tahsilat Planlama</button><button onClick={() => setTab('payments')} className={`px-4 py-2.5 rounded-xl text-xs font-black ${tab === 'payments' ? 'bg-emerald-600 text-white' : 'bg-white border border-emerald-200 text-emerald-800'}`}><WalletCards size={14} className="inline mr-1" /> Ödeme Planlama</button><button onClick={() => setTab('receipts')} className={`px-4 py-2.5 rounded-xl text-xs font-black ${tab === 'receipts' ? 'bg-amber-500 text-white' : 'bg-white border border-amber-200 text-amber-800'}`}><FileWarning size={14} className="inline mr-1" /> Fatura Bekleyen İşler ({uninvoiced.length})</button></div><div className="relative w-full lg:w-72"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Firma, yetkili veya telefon ara" className="w-full rounded-xl border border-emerald-200 bg-white py-2.5 pl-9 pr-3 text-xs outline-none focus:ring-2 focus:ring-emerald-200" /></div></div>
    {tab === 'collections' && <section className="grid xl:grid-cols-[1fr_330px] gap-5"><div className="rounded-2xl bg-white border border-emerald-100 shadow-sm overflow-hidden"><div className="p-4 border-b border-emerald-100"><h2 className="font-black text-emerald-950">Tahsilat öncelik sırası</h2><p className="text-xs text-slate-500 mt-1">En uzun süredir borçlu olan cari üstte gösterilir.</p></div><div className="divide-y divide-emerald-50">{filteredDebts.length ? filteredDebts.map((item, index) => <div key={item.customer.id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div className="flex gap-3"><div className={`w-8 h-8 rounded-xl flex items-center justify-center text-xs font-black ${index < 3 ? 'bg-rose-100 text-rose-700' : 'bg-emerald-100 text-emerald-700'}`}>{index + 1}</div><div><b className="text-sm text-emerald-950">{item.customer.title}</b><div className="flex flex-wrap gap-3 text-[11px] text-slate-500 mt-1"><span><Phone size={11} className="inline mr-1" />{item.customer.phone || 'Telefon yok'}</span><span>{item.customer.authorizedPerson || 'Yetkili belirtilmemiş'}</span><span>{item.oldestDays ? `${item.oldestDays} gündür vadesi geçmiş` : 'Güncel takip'}</span></div></div></div><div className="text-right"><b className="block text-base text-rose-700">{money(Math.max(item.customer.balance, item.invoiceTotal))}</b><button onClick={() => { setPlanCustomer(item.customer.id); setPlanAmount(String(Math.max(item.customer.balance, item.invoiceTotal))); }} className="mt-1 text-[11px] font-bold text-emerald-700 hover:underline">Tahsilat planı oluştur</button></div></div>) : <div className="p-10 text-center text-xs text-slate-500">Takip gerektiren cari bulunmuyor.</div>}</div></div><PlanForm title="Tahsilat planı" customerOptions={customers.map((item) => ({ id: item.id, label: item.title }))} customer={planCustomer} amount={planAmount} date={planDate} note={planNote} setCustomer={setPlanCustomer} setAmount={setPlanAmount} setDate={setPlanDate} setNote={setPlanNote} onSubmit={createCollectionPlan} /></section>}
    {tab === 'payments' && <section className="grid xl:grid-cols-[1fr_330px] gap-5"><div className="rounded-2xl bg-white border border-emerald-100 shadow-sm overflow-hidden"><div className="p-4 border-b border-emerald-100"><h2 className="font-black text-emerald-950">Planlanan şirket ödemeleri</h2><p className="text-xs text-slate-500 mt-1">Tedarikçi, personel ve diğer ödeme yükümlülüklerini vade sırasıyla takip edin.</p></div><div className="divide-y divide-emerald-50">{scheduledPayments.length ? scheduledPayments.map((item) => <div key={item.id} className="p-4 flex items-center justify-between gap-3"><div><b className="text-sm text-emerald-950">{item.recipientName}</b><div className="text-[11px] text-slate-500 mt-1">{item.category} · Vade: {item.dueDate}</div></div><div className="text-right"><b className="block text-rose-700">{money(item.amount)}</b><button onClick={() => markPaymentPaid(item.id)} className="text-[11px] font-bold text-emerald-700 mt-1">Ödendi olarak işaretle</button></div></div>) : <div className="p-10 text-center text-xs text-slate-500">Planlanmış ödeme yok.</div>}</div></div><PlanForm title="Ödeme planı" customerOptions={customers.map((item) => ({ id: item.title, label: item.title }))} customer={planCustomer} amount={planAmount} date={planDate} note={planNote} setCustomer={setPlanCustomer} setAmount={setPlanAmount} setDate={setPlanDate} setNote={setPlanNote} onSubmit={createPaymentPlan} /></section>}
    {tab === 'receipts' && <section className="rounded-2xl bg-white border border-amber-200 shadow-sm overflow-hidden"><div className="p-4 border-b border-amber-100 bg-amber-50"><h2 className="font-black text-amber-950">Fatura kesilmesi gereken iş makbuzları</h2><p className="text-xs text-amber-800 mt-1">Onaylanmış ancak faturaya dönüştürülmemiş işler yöneticilerin hatırlatması için burada tutulur.</p></div><div className="divide-y divide-amber-50">{uninvoiced.length ? uninvoiced.map((receipt) => <div key={receipt.id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><b className="text-sm text-emerald-950">{receipt.customerName}</b><div className="text-xs text-slate-500 mt-1">{receipt.receiptNo} · {receipt.date} · {receipt.craneCode} · {receipt.workingHours || 0} saat</div></div><button onClick={() => setTab('collections')} className="px-3 py-2 rounded-xl bg-amber-500 text-white text-xs font-bold">Cari takibe yönlendir</button></div>) : <div className="p-10 text-center text-xs text-slate-500">Fatura bekleyen onaylı iş makbuzu yok.</div>}</div></section>}
  </main>;
};

const PlanForm: React.FC<{ title: string; customerOptions: { id: string; label: string }[]; customer: string; amount: string; date: string; note: string; setCustomer: (value: string) => void; setAmount: (value: string) => void; setDate: (value: string) => void; setNote: (value: string) => void; onSubmit: (event: React.FormEvent) => void }> = ({ title, customerOptions, customer, amount, date, note, setCustomer, setAmount, setDate, setNote, onSubmit }) => <form onSubmit={onSubmit} className="rounded-2xl bg-white border border-emerald-100 p-4 shadow-sm space-y-3 h-fit"><div className="flex items-center gap-2"><CalendarClock size={17} className="text-emerald-600" /><h3 className="font-black text-emerald-950">{title} oluştur</h3></div><select required value={customer} onChange={(event) => setCustomer(event.target.value)} className="w-full rounded-xl border border-emerald-200 px-3 py-2.5 text-xs"><option value="">Firma / alıcı seçin</option>{customerOptions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><input required type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Tutar" className="w-full rounded-xl border border-emerald-200 px-3 py-2.5 text-xs" /><input required type="date" value={date} onChange={(event) => setDate(event.target.value)} className="w-full rounded-xl border border-emerald-200 px-3 py-2.5 text-xs" /><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Not / takip aksiyonu" rows={3} className="w-full rounded-xl border border-emerald-200 px-3 py-2.5 text-xs" /><button className="w-full rounded-xl bg-emerald-600 py-2.5 text-xs font-black text-white hover:bg-emerald-700"><CheckCircle2 size={14} className="inline mr-1" /> Planı kaydet</button></form>;
